# Generated by Django 5.1.4 on 2025-01-21 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('credits', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=40, null=True)),
                ('flagged_documents', models.IntegerField(default=0)),
                ('flash_style', models.IntegerField(blank=True, db_column='Flash_style', default=None, null=True, verbose_name='Flash card styling')),
                ('type', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tbl_user',
            },
        ),
    ]
