# Generated by Django 5.1.4 on 2025-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tbluser_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
