# Generated by Django 5.1.4 on 2025-01-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tbl_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='status',
        ),
    ]
