# Generated by Django 5.1.4 on 2025-01-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tbl_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
