# Generated by Django 5.1.4 on 2025-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tbl_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
