# Generated by Django 5.1.4 on 2025-01-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tbl_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
