# Generated by Django 5.1.4 on 2025-01-23 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tbl_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_document',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Course_ID', models.CharField(max_length=30, null=True)),
                ('Sem', models.IntegerField()),
                ('FilePath', models.CharField(max_length=255)),
                ('UploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField(default=True)),
                ('Discipline', models.CharField(max_length=50)),
                ('No_of_reports', models.IntegerField(default=0)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tbl_user')),
            ],
        ),
    ]
