# Generated by Django 5.1.4 on 2025-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tbl_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_document',
            name='P_key',
            field=models.TextField(default='none'),
        ),
    ]
